import { z } from 'zod'

const envSchema = z.object({
  NEXT_PUBLIC_FIREBASE_PUBLIC_API_KEY: z.string(),
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: z.string(),
  NEXT_PUBLIC_FIREBASE_PROJECT_ID: z.string(),
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: z.string(),
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: z.string(),
  NEXT_PUBLIC_FIREBASE_APP_ID: z.string(),
  NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: z.string(),
  NEXT_PUBLIC_BASE_URL: z.string().url(),
  // NEXT_PUBLIC_FOOTBALL_API: z.string(),
  // NEXT_PUBLIC_INTERNACIONAL_ID: z.string(),
  // NEXT_PUBLIC_YOUTUBE_CHANNEL_ID: z.string(),
  // NEXT_PUBLIC_YOUTUBE_MEMBERS_END_POINT: z.string(),
  // NEXT_PUBLIC_ENCRYPT_SECRET_KEY: z.string(),
  // NEXT_PUBLIC_GOOGLE_OAUTH_CLIENT_ID: z.string(),
  // NEXT_PUBLIC_GOOGLE_OAUTH_CLIENT_SECRET: z.string(),
  NEXT_PUBLIC_VDG_BACKEND_URL: z.string(),
  NEXT_PUBLIC_VDG_BACKEND_URL_DEV: z.string(),
  NEXT_PUBLIC_ENV: z.enum(['production', 'development']),
})

const parsedEnv = envSchema.safeParse({
  NEXT_PUBLIC_FIREBASE_PUBLIC_API_KEY:
    process.env.NEXT_PUBLIC_FIREBASE_PUBLIC_API_KEY,

  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN:
    process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,

  NEXT_PUBLIC_FIREBASE_PROJECT_ID: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,

  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET:
    process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,

  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID:
    process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,

  NEXT_PUBLIC_FIREBASE_APP_ID: process.env.NEXT_PUBLIC_FIREBASE_APP_ID,

  NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID:
    process.env.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID,

  NEXT_PUBLIC_BASE_URL: process.env.NEXT_PUBLIC_BASE_URL,

  // NEXT_PUBLIC_FOOTBALL_API: process.env.NEXT_PUBLIC_FOOTBALL_API,

  // NEXT_PUBLIC_INTERNACIONAL_ID: process.env.NEXT_PUBLIC_INTERNACIONAL_ID,

  // NEXT_PUBLIC_YOUTUBE_CHANNEL_ID: process.env.NEXT_PUBLIC_YOUTUBE_CHANNEL_ID,

  // NEXT_PUBLIC_YOUTUBE_MEMBERS_END_POINT: process.env.NEXT_PUBLIC_YOUTUBE_MEMBERS_END_POINT,

  // NEXT_PUBLIC_ENCRYPT_SECRET_KEY: process.env.NEXT_PUBLIC_ENCRYPT_SECRET_KEY,

  // NEXT_PUBLIC_GOOGLE_OAUTH_CLIENT_ID: process.env.NEXT_PUBLIC_GOOGLE_OAUTH_CLIENT_ID,

  // NEXT_PUBLIC_GOOGLE_OAUTH_CLIENT_SECRET: process.env.NEXT_PUBLIC_GOOGLE_OAUTH_CLIENT_SECRET,

  NEXT_PUBLIC_VDG_BACKEND_URL: process.env.NEXT_PUBLIC_VDG_BACKEND_URL,

  NEXT_PUBLIC_VDG_BACKEND_URL_DEV: process.env.NEXT_PUBLIC_VDG_BACKEND_URL_DEV,

  NEXT_PUBLIC_ENV: process.env.NEXT_PUBLIC_ENV,
})

if (!parsedEnv.success) {
  console.error(
    'Invalid environment variables',
    parsedEnv.error.flatten().fieldErrors,
  )

  throw new Error('Invalid environment variables')
}

export const env = parsedEnv.data
